# add stages here 
stages:
  LoadData:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
    - src/stage_01_get_data.py
    - src/utils/common.py
    - configs/config.yaml
    - src/cloud_sync/object_storage.py
    outs:
    - dataset/

  PrepareModel:
    cmd: python src/stage_02_prepare_model.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_02_prepare_model.py
    - src/cloud_sync/object_storage.py
    - src/utils/common.py
    - src/ml/model.py
    - configs/config.yaml
    - params.yaml
    params:
      - IMAGE_SIZE
      - CLASSES
      - LEARNING_RATE
      - FREEZE_ALL
      - FREEZE_TILL
      - LOSS_FUNCTION
      - METRICS
    outs:
    - artifacts/models/base_model.h5
    - artifacts/models/untrained_full_model.h5

  TraningAndEvaluation:
    cmd: python src/stage_03_train_evaluate.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_03_train_evaluate.py
    - src/cloud_sync/object_storage.py
    - dataset/
    - artifacts/models/untrained_full_model.h5
    - src/utils/common.py
    - src/ml/model.py
    - configs/config.yaml
    - params.yaml
    params:
      - VALIDATION_SPLIT_SIZE
      - BATCH_SIZE
      - DATA_AUGMENTATION
      - EARLY_STOPPING_PATIENCE
      - LEARNING_RATE_PATIENCE
      - EPOCHS
      - TRAIN_FORM_CHECKPOINT
    outs:
    - artifacts/checkpoints/
    - artifacts/model_evaluation/
    - artifacts/models/trained_model.h5
    - logs/tensorboard_logs_dir/

  ModelBlessing:
    cmd: python src/stage_04_model_blessing.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_04_model_blessing.py
    - artifacts/models/trained_model.h5
    - src/cloud_sync/object_storage.py
    - src/utils/common.py
    - src/ml/model.py
    - configs/config.yaml
    - params.yaml
    params:
      - BLESSING_THRESHOLD_COMPARISION
      - MODEL_BLESSING_THRESHOLD
    outs:
    - artifacts/models/blessed_model.h5